// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI agent that does sentiment analysis on messages from the contact form.
 *
 * - analyzeContactFormSentiment - A function that handles the sentiment analysis.
 * - AnalyzeContactFormSentimentInput - The input type for the analyzeContactFormSentiment function.
 * - AnalyzeContactFormSentimentOutput - The return type for the analyzeContactFormSentiment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeContactFormSentimentInputSchema = z.object({
  message: z.string().describe('The message from the contact form.'),
});
export type AnalyzeContactFormSentimentInput = z.infer<
  typeof AnalyzeContactFormSentimentInputSchema
>;

const AnalyzeContactFormSentimentOutputSchema = z.object({
  sentiment: z
    .string()
    .describe(
      'The sentiment of the message, can be positive, negative, or neutral.'
    ),
  urgency: z
    .string()
    .describe(
      'The urgency of the message, can be urgent, or not urgent, based on the sentiment and content of the message.'
    ),
});
export type AnalyzeContactFormSentimentOutput = z.infer<
  typeof AnalyzeContactFormSentimentOutputSchema
>;

export async function analyzeContactFormSentiment(
  input: AnalyzeContactFormSentimentInput
): Promise<AnalyzeContactFormSentimentOutput> {
  return analyzeContactFormSentimentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeContactFormSentimentPrompt',
  input: {schema: AnalyzeContactFormSentimentInputSchema},
  output: {schema: AnalyzeContactFormSentimentOutputSchema},
  prompt: `You are an AI expert in sentiment analysis.

You will analyze the sentiment of the message from the contact form, and determine the urgency of the message.

Message: {{{message}}}

Considerations for urgency:
- Negative sentiment often indicates urgency, especially if the user is reporting a problem or expressing dissatisfaction.
- The user may explicitly state that the matter is urgent.
- The user may be reporting a security vulnerability.
- The user may be reporting a legal issue.
- The user may be expressing anger or frustration.
- The user may be threatening legal action.

Set the sentiment and urgency output fields appropriately.`,
});

const analyzeContactFormSentimentFlow = ai.defineFlow(
  {
    name: 'analyzeContactFormSentimentFlow',
    inputSchema: AnalyzeContactFormSentimentInputSchema,
    outputSchema: AnalyzeContactFormSentimentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
